---
title: "Exercise 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fork the RBigData/KPMS-IT4I-EX GitHub repository

We will clone an existing GitHub repository to karolina and run it. Then play with some Unix commands. In order to have your own work version of the repository, you need to fork it on GitHub and then use RSudio to bring to your laptop. After cloning the forked version to karolina you are ready for a working code pipeline from your laptop to the cluster.

## Fork a repository and work on it with RStudio

1. Log into your GitHub account
2. Find the RBigData/KPMS-IT4I-EX repository and `Fork` it to your account
3. Get its clone url (the green Code button)
4. Open yout RSttudio and start a New Project with Version Control using the url

## Clone your KPMS-IT4I-EX repository to Karolina

1. Open a terminal window and login to karolina.it4i.cz
2. Copy your KPMS-IT4I-EX "clone" url (the green Code button)
3. In Karolina terminal `git clone paste_clone_url_here`
4. `cd KPMS-IT4I-EX`
5. Use Unix commands to look at the contents
6. Submit the shell script `rf_karolina_pbs.sh`
7. Use Unix commands to look at output files `rf.e` and `rf.o`

## Reproduce the run time graph from the Lecture03 with Karolina times

1. On your laptop RStudio, edit the shell script in your KPMS-IT4I-EX repository to produce times for 1, 2, 4, 8, 16, 32, 64, and 128 cores
2. Commit and push your changes to GitHub
3. Pull them to Karolina (`git pull` in Karolina terminal)
4. Submit the script with `qsub`
5. Use the resulting times to make a run time plot
